### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by yangfangming** [ohmeta/metapi#14]
https://github.com/ohmeta/metapi/blob/85ca61c8e8f485dd5d562c34d16ae5987bf78a4a/metapi/cluster.yaml#L77 to #L120  the output path is inconsistent with the "logs" directory.

**Comment by alienzj** [comment]
Hi, thanks for bug report.
Now, see https://github.com/ohmeta/metapi/commit/52d2987ab9ebc5997f4771e327c8b0db2cb67dbd, fixed.
