### ISSUE TITLE
error ： r1 should be r

### ISSUE THREAD

**Issue by juyanmei** [ohmeta/metapi#3]
https://github.com/ohmeta/metapi/blob/66fdd5a5e4424a9469fe7370cc7a26880e660625/metapi/rules/trimming.smk#L225

**Comment by alienzj** [comment]
@juyanmei Thanks  very much!
Now fixed https://github.com/ohmeta/metapi/commit/c6da7dbb02f38fe8c6cfe503a8ef4cf1a6fc1653
