### ISSUE TITLE
[A little feedback]

### ISSUE THREAD

**Issue by houhaiyang** [ohmeta/metapi#39]
After I installed it with the command: 
pip3 install metapi==2.1.1
"metapi --help" will prompt: 
modulenotfounderror: no module named' seaborn'
So I need to execute the command: pip install seaborn

**Comment by alienzj** [comment]
Dear @houhaiyang, thanks for your feedback.
I will fix the dependency issues when publish next version.

**Comment by alienzj** [comment]
Updated to v2.1.2: https://github.com/ohmeta/metapi/releases/tag/v2.1.2
