### ISSUE TITLE
Need to install those software before running?

### ISSUE THREAD

**Issue by wangjiaxuan666** [ohmeta/metapi#40]
Thank you for providing such good software which can analysis the meta workflow.

when I run 

```
metapi mag_wf all --use-conda --run-local
```
and I get the config.yml 

Before I run the workflow ,need I download those software which in requirement? and export to the env path?

**Comment by alienzj** [comment]
Thanks for reporting this issues.

Most of rules in metapi have been configured using conda env.
But there are still some software not yet.
In the near future, I will update all to use conda env.

Currently,
For conda env part, you can run:
```
metapi mag_wf all --use-conda --cores 8 --conda-create-envs-only # only create envrionments
# or 
metapi mag_wf all --use-conda --cores 8 --run-local # create environments and run it
```
then snakeamke will call mamba to create environment automatically.
After setup the environment, snakemake will activate it and run the specific cmd declared in the metapi rule.
Don't worry about the environment, when you run metapi again, sankemake will find it.
If the envs file updated, snakemake will create environment again.


For non conda env part, maybe you should install some softwares if it hasn't been installed yet.
```
mamba install fastp bwa bowtie2 megahit spades multiqc fastqc seqkit samtools
```

Hope it can help you.

**Comment by alienzj** [comment]
Dear @wangjiaxuan666,
Now, https://github.com/ohmeta/metapi/releases/tag/v2.3.0 support running metapi without installing any software manually, just run it with parameter `--use-conda`.
