### ISSUE TITLE
add deduplication option

### ISSUE THREAD

**Issue by juyanmei** [ohmeta/metapi#41]
Since fastp v0.22.0, fastp supports deduplication for FASTQ data. Specify -D or --dedup to enable this option. https://github.com/OpenGene/fastp#duplication-rate-and-deduplication
Hope you could add this option in metapi. Thanks~

**Comment by alienzj** [comment]
Great! Thanks for your suggestion.
Hope can support this feature at the next release.

**Comment by alienzj** [comment]
Now metapi v2.4.0 (https://github.com/ohmeta/metapi/releases/tag/v2.4.0) support `fastp` with parameter `--dedup`.

**Comment by alienzj** [comment]
https://github.com/ohmeta/metapi/blob/dev/metapi/rules/trimming.smk#L122
