### ISSUE TITLE
add save_host_reads option

### ISSUE THREAD

**Issue by juyanmei** [ohmeta/metapi#42]
For samples with a high ratio of host reads, the host reads maybe need to be saved for further analysis like GWAS. Is it necessary to add this option?

**Comment by alienzj** [comment]
It was already implemented at metapi rmhost module.

For example,
if specific `params::rmhost::save_bam` to `True`, and do rmhost using `bwa` or `bowtie2` or `minimap2`, user will get bam output from here: `results/bam/{sample}/{sample}.align2host.sorted.bam`.

Hope this helps!

**Comment by juyanmei** [comment]
Great！
